---
version: "3.9"
networks:
  hoprd-node_hoprnet:
    external: true

volumes:
  exitapp_data: {}

services:
  uhttp-exit-app:
    image: "${UHTTP_EXITAPP_IMAGE}"
    restart: always
    platform: linux/amd64
    container_name: uhttp-exit-app
    hostname: uhttp-exit-app
    networks:
      - hoprd-node_hoprnet
    environment:
      - "DEBUG=*"
      - "UHTTP_EA_DATABASE_FILE=/app/db/store.sqlite3"
      - "UHTTP_EA_DISCOVERY_PLATFORM_ENDPOINT=https://discovery-platform.prod.hoprnet.link"
      - "UHTTP_EA_HOPRD_ENDPOINT=http://hoprd:3001"
    env_file:
      - .env-secrets
    volumes:
      - exitapp_data:/app/db
    deploy:
      resources:
        reservations:
          memory: "${UHTTP_EXITAPP_MEM_REQUEST}"
        limits:
          memory: "${UHTTP_EXITAPP_MEM_LIMIT}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "7"
    profiles:
      - exit-app
