---
networks:
  hoprnet:
    driver: bridge

volumes:
  exitapp_data: {}
  hoprd_data: {}

services:
  hoprd:
    image: "${HOPRD_IMAGE}"
    restart: unless-stopped
    pull_policy: always
    platform: ${DOCKER_PLATFORM}
    container_name: hoprd
    hostname: hoprd
    stop_signal: SIGINT
    networks:
      - hoprnet
    ports:
      - "${HOPRD_P2P_PORT}:${HOPRD_P2P_PORT}/tcp"
      - "${HOPRD_P2P_PORT}:${HOPRD_P2P_PORT}/udp"
      - "${HOPRD_API_PORT}:3001"
    env_file:
      - .env-secrets
    environment:
      - "RUST_LOG=${HOPRD_LOG_LEVEL}"
      - RUST_BACKTRACE=full
      - HOPRD_CONFIGURATION_FILE_PATH=/app/hoprd.cfg.yaml
      - HOPRD_API_PORT=3001
      # - OPENTELEMETRY_COLLECTOR_URL=http://server.
    volumes:
      - hoprd_data/:/app/
    deploy:
      resources:
        reservations:
          memory: "${HOPRD_MEM_REQUEST}"
        limits:
          memory: "${HOPRD_MEM_LIMIT}"
    logging:
      driver: json-file
      options:
        max-size: "${HOPRD_LOG_MAX_SIZE}"
        max-file: 5

  uhttp-exit-app:
    image: "${UHTTP_EXITAPP_IMAGE}"
    restart: always
    platform: linux/amd64
    container_name: uhttp-exit-app
    hostname: uhttp-exit-app
    networks:
      - hoprd-node_hoprnet
    environment:
      - "DEBUG=*"
      - "UHTTP_EA_DATABASE_FILE=/app/db/store.sqlite3"
    env_file:
      - .env-secrets
    volumes:
      - exitapp_data:/app/db
    deploy:
      resources:
        reservations:
          memory: "${UHTTP_EXITAPP_MEM_REQUEST}"
        limits:
          memory: "${UHTTP_EXITAPP_MEM_LIMIT}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "7"

  hopr-admin:
    image: "${HOPR_ADMIN_IMAGE}"
    restart: unless-stopped
    platform: ${DOCKER_PLATFORM}
    container_name: admin
    hostname: admin
    ports:
      - "${HOPR_ADMIN_PORT}:80"
    networks:
      - hoprnet
    deploy:
      resources:
        reservations:
          memory: "${HOPR_ADMIN_MEM_REQUEST}"
        limits:
          memory: "${HOPR_ADMIN_MEM_LIMIT}"
