---
networks:
  hoprnet:
    driver: bridge

volumes:
  exit-app_data: {}
  hoprd_data: {}

services:
  hoprd:
    image: "${HOPRD_IMAGE}"
    restart: unless-stopped
    pull_policy: always
    stop_signal: SIGINT
    platform: ${DOCKER_PLATFORM}
    container_name: hoprd
    hostname: hoprd
    stop_signal: SIGINT
    networks:
      - hoprnet
    ports:
      - "${HOPRD_P2P_PORT}:${HOPRD_P2P_PORT}/tcp"
      - "${HOPRD_P2P_PORT}:${HOPRD_P2P_PORT}/udp"
      - "${HOPRD_API_PORT}:3001"
    env_file:
      - .env-secrets
    environment:
      - "RUST_LOG=${HOPRD_LOG_LEVEL}"
      - RUST_BACKTRACE=full
      - HOPRD_CONFIGURATION_FILE_PATH=/app/hoprd.cfg.yaml
      - HOPRD_API_PORT=3001
    volumes:
      - ./hoprd_data:/app
    deploy:
      resources:
        reservations:
          memory: "${HOPRD_MEM_REQUEST}"
        limits:
          memory: "${HOPRD_MEM_LIMIT}"
    logging:
      driver: json-file
      options:
        max-size: "${HOPRD_LOG_MAX_SIZE}"
        max-file: 5

  hopr-admin:
    image: "${HOPR_ADMIN_IMAGE}"
    restart: unless-stopped
    pull_policy: always
    platform: ${DOCKER_PLATFORM}
    container_name: admin
    hostname: admin
    networks:
      - hoprnet
    ports:
      - "${HOPR_ADMIN_PORT}:80"
    deploy:
      resources:
        reservations:
          memory: "${HOPR_ADMIN_MEM_REQUEST}"
        limits:
          memory: "${HOPR_ADMIN_MEM_LIMIT}"

  uhttp-exit-app:
    image: "${UHTTP_EXITAPP_IMAGE}"
    depends_on:
      - hoprd
    restart: unless-stopped
    pull_policy: always
    platform: ${DOCKER_PLATFORM}
    container_name: uhttp-exit-app
    hostname: uhttp-exit-app
    networks:
      - hoprnet
    env_file:
      - .env-secrets
    environment:
      - "DEBUG=*"
      - "UHTTP_EA_DATABASE_FILE=/app/db/store.sqlite3"
      - "UHTTP_EA_HOPRD_ENDPOINT=http://hoprd:${HOPRD_API_PORT}"

    volumes:
      - ./exit-app_data:/app/db
    deploy:
      resources:
        reservations:
          memory: "${UHTTP_EXITAPP_MEM_REQUEST}"
        limits:
          memory: "${UHTTP_EXITAPP_MEM_LIMIT}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "7"
