---
global:
  scrape_interval: 15s
  external_labels:
    monitor: "hoprd"
scrape_configs:
  - job_name: "hoprd"
    scrape_interval: 15s
    authorization:
      type: Bearer
      # Replace the below credentials with an API token if changed in the hoprd-config
      credentials: "^Pr1vacyasafirstCLASSpr0ductfe4turemadeEASY^"
    static_configs:
      - targets: ["hoprd:3001"]
        labels:
          job: "hoprd-node-1"
          namespace: "Specify the name of the company/investor"
          hoprd_peer_id: "Specify the peer ID of the hoprd node"
          hoprd_network: "dufour" # Posible values are dufour, rotsee
          hoprd_address: "Specify the native address of the hoprd node"
    metrics_path: /api/v3/node/metrics
  - job_name: "cadvisor"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          group: "cadvisor"
          image: "cadvisor"
  - job_name: "node"
    scrape_interval: 10s
    static_configs:
      - targets: ["nodeexporter:9100"]
