{
 "title": "Hoprd Node",
 "description": "Metrics for Hoprd nodes",
 "tags": [
  "hopr",
  "Home"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod_name", "label": "Node Name", "query": { "query": "label_values(hopr_up,job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(hopr_up{job=\"${pod_name}\"},instance)"
    }
   },
   {
    "name": "native_address",
    "label": "Ethereum Address",
    "query": {
     "query": "label_values(hopr_up{job=~\"$pod_name\"},hoprd_address)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(hopr_up{job=~\"$pod_name\"},namespace)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "label_values(hopr_up{job=~\"$pod_name\"},hoprd_network)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "canvas", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 } },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "hopr_lib_version{job=~\"$pod_name\"}",
     "legendFormat": "{{hoprd_network}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hopr_lib_version{job=~\"$pod_name\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hopr_network_health{job=~\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(hopr_indexer_block_number{job=~\"${pod_name}\"} - 29000000) / (hopr_chain_head_block_number{job=~\"${pod_name}\"} - 29000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hopr_up{job=~\"${pod_name}\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(hopr_up{job=~\"${pod_name}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "High Quality Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hopr_peers_by_quality{job=~\"${pod_name}\", quality=\"high\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low quality peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hopr_peers_by_quality{job=~\"${pod_name}\", quality=\"low\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total messages sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_packets_count{job=~\"${pod_name}\", type=\"sent\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing channels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(hopr_channel_balances{direction=\"out\", job=~\"${pod_name}\"} != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total messages received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_packets_count{job=~\"${pod_name}\", type=\"received\"}[$__range])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Total messages forwarded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_packets_count{job=~\"${pod_name}\", type=\"forwarded\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming channels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hopr_channel_balances{direction=\"in\", job=~\"${pod_name}\"} != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p2p open connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hopr_transport_p2p_opened_connection_count{job=~\"${pod_name}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº messages received per minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_packets_count{job=~\"${pod_name}\", type=\"received\"}[1m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Nº messages forwarded per minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_packets_count{job=~\"${pod_name}\", type=\"forwarded\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº message sent per minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_packets_count{job=~\"${pod_name}\", type=\"sent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mixer delay (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hopr_mixer_average_packet_delay{job=\"${pod_name}\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Created tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_created_tickets_count{job=~\"${pod_name}\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agregated tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_aggregated_tickets_count{job=~\"${pod_name}\"}[$__range])",
     "legendFormat": "Agregated"
    }
   ]
  },
  {
   "title": "Performed ticket aggregations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_strategy_aggregating_aggregation_count{job=~\"${pod_name}\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Winning tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_winning_tickets_count{job=~\"${pod_name}\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ticket probability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_winning_tickets_count{job=~\"${pod_name}\"}[$__range]) / increase(hopr_packets_count{job=~\"${pod_name}\", type=\"received\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Losing tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_losing_tickets_count{job=~\"${pod_name}\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Message latency (sec)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hopr_message_latency_sec_bucket{job=~\"${pod_name}\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages latency (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(hopr_message_latency_sec_sum{job=~\"${pod_name}\"}[$__rate_interval]) \n/\nrate(hopr_message_latency_sec_count{job=~\"${pod_name}\"}[$__rate_interval]) > 0    \n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Message rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(hopr_packets_count{job=~\"${pod_name}\", type=\"received\"}[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(hopr_packets_count{job=~\"${pod_name}\", type=\"sent\"}[$__rate_interval])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(hopr_packets_count{job=~\"${pod_name}\", type=\"forwarded\"}[$__rate_interval])",
     "legendFormat": "Forwarded"
    }
   ]
  },
  {
   "title": "Message latency quantiles (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(hopr_message_latency_sec_bucket{job=~\"${pod_name}\"}[$__rate_interval])))",
     "legendFormat": "Quantile 50%"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (job, le) (rate(hopr_message_latency_sec_bucket{job=~\"${pod_name}\"}[10m])))",
     "legendFormat": "Quantile 90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(hopr_message_latency_sec_bucket{job=~\"${pod_name}\"}[10m])))",
     "legendFormat": "Quantile 95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(hopr_message_latency_sec_bucket{job=~\"${pod_name}\"}[10m])))",
     "legendFormat": "Quantile 99%"
    }
   ]
  },
  {
   "title": "Message path length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(hopr_path_length_sum{job=\"${pod_name}\"}[$__rate_interval])\n/\nrate(hopr_path_length_count{job=\"${pod_name}\"}[$__rate_interval])",
     "legendFormat": "Hops"
    }
   ]
  },
  { "title": "RPC calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Nº Rpc calls",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by (call) (increase(hopr_rpc_call_count{job=~\"$pod_name\", result=\"success\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (call) (increase(hopr_rpc_call_count{job=~\"$pod_name\", result!=\"success\"}[$__rate_interval]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "RPC calls latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(hopr_rpc_call_time_sec_count{job=~\"${pod_name}\"}[$__rate_interval]) \n/\nrate(hopr_rpc_call_time_sec_count{job=~\"${pod_name}\"}[$__rate_interval]) > 0",
     "legendFormat": "{{call}}"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Network health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "avg(hopr_network_health{job=~\"${pod_name}\"}) by (job)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Opened channels",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum by (counterparty,direction) (hopr_channel_balances{job=~\"${pod_name}\"} != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "increase(hopr_http_api_call_count{job=\"${pod_name}\", status=~\"2.*\"}[$__rate_interval]) > 0",
     "legendFormat": "{{exported_endpoint}}- {{method}}"
    }
   ]
  },
  {
   "title": "API latency ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(hopr_http_api_call_timing_sec_sum{job=\"${pod_name}\"}[$__rate_interval])\n/\nrate(hopr_http_api_call_timing_sec_count{job=\"${pod_name}\"}[$__rate_interval])\n > 0",
     "legendFormat": "{{exported_endpoint}} - {{method}}"
    }
   ]
  },
  {
   "title": "Heartbeat response time (sec)",
   "type": "bargauge",
   "description": "Measures total time it takes to probe other nodes (in seconds)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hopr_heartbeat_round_time_sec_bucket{job=~\"${pod_name}\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Strategies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "increase(hopr_chain_actions_count{job=\"${pod_name}\"}[$__rate_interval]) ",
     "legendFormat": "{{action}} - {{result}}"
    }
   ]
  },
  {
   "title": "Ping response time (sec)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hopr_ping_time_sec_bucket{job=~\"${pod_name}\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heartbeat pings rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(hopr_heartbeat_pings_count{job=\"${pod_name}\", success=\"true\"}[$__rate_interval])",
     "legendFormat": "Succeed"
    },
    {
     "expr": "increase(hopr_heartbeat_pings_count{job=~\"${pod_name}\", success=\"false\"}[$__rate_interval])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Peers by quality",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum by(quality,job) (hopr_peers_by_quality{job=~\"${pod_name}\", quality=\"high\"})",
     "legendFormat": "High quality peers"
    },
    {
     "expr": "sum by(quality,job) (hopr_peers_by_quality{job=~\"${pod_name}\",quality=\"low\"})",
     "legendFormat": "Low quality peers"
    }
   ]
  }
 ]
}